version: '3'

services:
  ftp-server:
    image: "delfer/alpine-ftp-server"
    container_name: "ftp-server"
    ports:
      - "5021:21"
      - "21000-21010:21000-21010"
    volumes:
      - "./ftp:/home/devftp/"
    environment:
      USERS: "devftp|dev123"
      ADDRESS: "localhost"
